{/* <title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" /> */}
import { useEvmNativeBalance } from '@moralisweb3/next';
import IndexPresentation from '../components/IndexPresentation';
import MyCarousel from '../components/MyCarousel';
import MyOwlCarousel from '../components/MyOwlCarousel';
import Image from 'next/image';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

export default function Home(props) {
  
  const address = "0x291DCCdF0CfF6715A1350A0c8664a5A4Cd38A194";
  const { data: nativeBalance } = useEvmNativeBalance({ address });

  return (
    <Container>
      <Row style={{paddingBottom: "90px"}}>
        <Col md={6}><IndexPresentation /></Col>
        <Col md={6} bsPrefix="d-none d-sm-block col"><MyCarousel nfts={[{id: 0, address: "efsdfsfsd", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR08vz0MsFRneW3Gvxp0-7cV6H7QEOQ25ggclc-rtY&s", name: "Castor", price: 10},
        {id: 0, address: "efsdfsfsd", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR08vz0MsFRneW3Gvxp0-7cV6H7QEOQ25ggclc-rtY&s", name: "Castor 1", price: 10},
        {id: 0, address: "efsdfsfsd", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR08vz0MsFRneW3Gvxp0-7cV6H7QEOQ25ggclc-rtY&s", name: "Castor 2", price: 15},
        {id: 0, address: "efsdfsfsd", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR08vz0MsFRneW3Gvxp0-7cV6H7QEOQ25ggclc-rtY&s", name: "Castor 3", price: 20}
      ]} /></Col>
      </Row>
      <Row>
        {/* <h3>Wallet: {address}</h3>
        <h3>Native Balance: {nativeBalance?.balance.ether} ETH</h3> */}
        <Col lg={12} bsPrefix="text-center col"><MyOwlCarousel /></Col>
      </Row>
  </Container>
  )
}
